package database;


import com.mysql.jdbc.exceptions.MySQLSyntaxErrorException;
import java.awt.Color;
import static java.awt.SystemColor.text;
import java.awt.Toolkit;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 17g01acs028
 */
public class create_database extends javax.swing.JFrame {

    Connection conn;
        ResultSet rs,r;
        Statement m;
        PreparedStatement st;
     
    public create_database() throws SQLException {
        initComponents();
        showdb();
        rows.setText("2");
        tb3.setEditingColumn(-1);
        tb3.setEditingRow(-1);
        rows.setText("1");
        kk.removeAll();
        kk.revalidate();
        kk.repaint();
        kk.add(kk6);
        kk.revalidate();
        kk.repaint();
        tc.setEditable(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        he = new javax.swing.JLabel();
        kk = new javax.swing.JPanel();
        kk2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        db = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        col = new javax.swing.JComboBox<>();
        kk3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        table1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rows = new javax.swing.JTextField();
        kk6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        kk4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tak = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        kk5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        tc = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        kk7 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tbt = new javax.swing.JLabel();
        kk8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb4 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        ll = new javax.swing.JScrollPane();
        tb3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 204));
        jLabel1.setText("new");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Database name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb);

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        he.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        he.setForeground(new java.awt.Color(102, 0, 153));
        he.setText("server 127.0.0.1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(he, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(he, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        kk.setLayout(new java.awt.CardLayout());

        jLabel3.setText("name");

        jButton1.setText("create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        col.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Collation", "int", "latin", "string" }));

        javax.swing.GroupLayout kk2Layout = new javax.swing.GroupLayout(kk2);
        kk2.setLayout(kk2Layout);
        kk2Layout.setHorizontalGroup(
            kk2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kk2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(db, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(col, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );
        kk2Layout.setVerticalGroup(
            kk2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kk2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(kk2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1)
                    .addComponent(col, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        kk.add(kk2, "card2");

        jLabel4.setText("name");

        jButton2.setText("create");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("rows");

        rows.setText("2");

        javax.swing.GroupLayout kk3Layout = new javax.swing.GroupLayout(kk3);
        kk3.setLayout(kk3Layout);
        kk3Layout.setHorizontalGroup(
            kk3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kk3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addComponent(table1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rows, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(82, 82, 82))
        );
        kk3Layout.setVerticalGroup(
            kk3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kk3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(kk3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(table1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton2)
                    .addComponent(jLabel2)
                    .addComponent(rows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        kk.add(kk3, "card2");

        jLabel5.setBackground(new java.awt.Color(51, 0, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 204));
        jLabel5.setText("Welcome to steve Server");

        javax.swing.GroupLayout kk6Layout = new javax.swing.GroupLayout(kk6);
        kk6.setLayout(kk6Layout);
        kk6Layout.setHorizontalGroup(
            kk6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kk6Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        kk6Layout.setVerticalGroup(
            kk6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kk6Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel5)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        kk.add(kk6, "card2");

        tak.setColumns(20);
        tak.setRows(5);
        jScrollPane4.setViewportView(tak);

        jButton6.setText("go");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("clear");

        javax.swing.GroupLayout kk4Layout = new javax.swing.GroupLayout(kk4);
        kk4.setLayout(kk4Layout);
        kk4Layout.setHorizontalGroup(
            kk4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kk4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );
        kk4Layout.setVerticalGroup(
            kk4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kk4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kk4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)))
        );

        kk.add(kk4, "card2");

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane5.setViewportView(ta);

        tc.setBackground(new java.awt.Color(240, 240, 240));
        tc.setColumns(20);
        tc.setRows(5);
        jScrollPane6.setViewportView(tc);

        jButton9.setText("Insert");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("update");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("delete");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("select *");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("select");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("go");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("clear");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kk5Layout = new javax.swing.GroupLayout(kk5);
        kk5.setLayout(kk5Layout);
        kk5Layout.setHorizontalGroup(
            kk5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kk5Layout.createSequentialGroup()
                .addGroup(kk5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kk5Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10)
                        .addGap(28, 28, 28)
                        .addComponent(jButton11)
                        .addGap(34, 34, 34)
                        .addComponent(jButton12)
                        .addGap(35, 35, 35)
                        .addComponent(jButton13)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
            .addGroup(kk5Layout.createSequentialGroup()
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton14)
                .addContainerGap())
        );
        kk5Layout.setVerticalGroup(
            kk5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kk5Layout.createSequentialGroup()
                .addGroup(kk5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kk5Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(kk5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton10)
                            .addComponent(jButton11)
                            .addComponent(jButton12)
                            .addComponent(jButton13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kk5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton15)))
        );

        kk.add(kk5, "card2");

        jButton16.setText("DROP");

        jLabel6.setText("Tables");

        javax.swing.GroupLayout kk7Layout = new javax.swing.GroupLayout(kk7);
        kk7.setLayout(kk7Layout);
        kk7Layout.setHorizontalGroup(
            kk7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kk7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kk7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kk7Layout.createSequentialGroup()
                        .addComponent(tbt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 424, Short.MAX_VALUE)
                        .addComponent(jButton16)
                        .addGap(53, 53, 53))
                    .addGroup(kk7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        kk7Layout.setVerticalGroup(
            kk7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kk7Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(kk7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton16)
                    .addComponent(tbt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        kk.add(kk7, "card2");

        tb4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb4);

        javax.swing.GroupLayout kk8Layout = new javax.swing.GroupLayout(kk8);
        kk8.setLayout(kk8Layout);
        kk8Layout.setHorizontalGroup(
            kk8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        );
        kk8Layout.setVerticalGroup(
            kk8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );

        kk.add(kk8, "card2");

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tables"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb2);

        jButton3.setText("Browse");

        jButton4.setText("sql");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Structure");

        jButton8.setText("drop");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton8)))
        );

        tb3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "field", "type", "null", "key", "default", "extra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ll.setViewportView(tb3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ll, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(ll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 38, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(975, 536));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
       
        kk.removeAll();
        kk.revalidate();
        kk.repaint();
        kk.add(kk2);
        kk.revalidate();
        kk.repaint();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
he.setText(he.getText()+">>database: "+db.getText());
        if(!db.getText().isEmpty()){     try {
             
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "");
            String q="create database "+db.getText()+"";
            st=conn.prepareCall(q);
            st.execute();
            JOptionPane.showMessageDialog(null,"Created");
             kk.removeAll();
            kk.revalidate();
            kk.repaint();
            kk.add(kk3);
            kk.revalidate();
            kk.repaint();
            
        } catch (SQLException ex) {
            Logger.getLogger(create_database.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null,ex);
        }
    
       
       }else{JOptionPane.showMessageDialog(null,"Enter database name!!!!!");}
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    he.setText(he.getText()+">>Table: "+table1.getText());
        String y=rows.getText();
        if(Integer.parseInt(y)<2){
        JOptionPane.showMessageDialog(null,"Default rows no is two!!");
        }    
else{  if(!table1.getText().isEmpty())  { 
          showdb();
         this.setVisible(false);
         tables t=new tables();
         t.setVisible(true);
       
    }else{JOptionPane.showMessageDialog(null,"Tables name can't be empty");}
  
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        // TODO add your handling code here:
        showtb();
       
            
    }//GEN-LAST:event_tbMouseClicked

    private void tb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb2MouseClicked
        // TODO add your handling code here:
        
             tb3.setVisible(true);
         int i=tb.getSelectedRow();
          try {
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+tb.getValueAt(i,0).toString()+"", "root", "");
                          int v=tb2.getSelectedRow();

            String query="desc "+tb2.getValueAt(v, 0)+"";
            st=conn.prepareStatement(query);
            rs=st.executeQuery();
             String query1="select * from "+tb2.getValueAt(v, 0)+"";
            st=conn.prepareStatement(query1);
              r = st.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(create_database.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(null,ex);
        }
          kk.removeAll();
            kk.revalidate();
            kk.repaint();
            kk.add(kk8);
            kk.revalidate();
            kk.repaint();
           tb3.setModel(DbUtils.resultSetToTableModel(rs));
            tb4.setModel(DbUtils.resultSetToTableModel(r));
    }//GEN-LAST:event_tb2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
     if(tb.isColumnSelected(0))  { kk.removeAll();
        kk.revalidate();
        kk.repaint();
        kk.add(kk4);}
   if(tb.isColumnSelected(0)&&tb2.isColumnSelected(0)){
         ta.setText("SELECT * FROM `"+tb2.getValueAt(0, 0).toString()+"` WHERE 1");
         ta.getLineWrap();
         ta.getWrapStyleWord();
         ta.setLineWrap(true);
         kk.removeAll();
         kk.revalidate();
         kk.repaint();
         kk.add(kk5);
        
        tc.setText(tb3.getValueAt(0,0).toString());
         tc.append(tb2.getValueAt(1,0).toString());
         tc.append(tb2.getValueAt(2,0).toString());
         tc.append(tb2.getValueAt(3,0).toString());
     } if(!tb.isColumnSelected(0)&&!tb2.isColumnSelected(0)){
     JOptionPane.showMessageDialog(null,"NO DATASASE IS SELECTED");
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         ta.setText("SELECT * FROM `"+tb2.getValueAt(0, 0).toString()+"` WHERE 1");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        ta.setText("UPDATE  `"+tb2.getValueAt(0, 0).toString()+"` SET  VALUE  WHERE 1");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         ta.setText("DELETE  FROM   `"+tb2.getValueAt(0, 0).toString()+"`  WHERE 0");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        ta.setText("SELECT  FIELD_NAME  FROM  `"+tb2.getValueAt(0, 0).toString()+"`  WHERE 1");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        ta.setText("INSERT INTO  `"+tb2.getValueAt(0, 0).toString()+"` (FIELDS)  VALUES  (VALUES)  WHERE 1");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        ta.setText("");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       
        try {
            int i=tb.getSelectedRow();
            String y=tak.getText().toLowerCase();
           
             if(y.contains("select")){
             kk.removeAll();
            kk.revalidate();
            kk.repaint();
            kk.add(kk8);
            kk.revalidate();
            kk.repaint();
           st=conn.prepareStatement(y);
              r = st.executeQuery();
            tb4.setModel(DbUtils.resultSetToTableModel(r));
            }
             else if(y.contains("show")){
           
             kk.removeAll();
            kk.revalidate();
            kk.repaint();
            kk.add(kk8);
            kk.revalidate();
            kk.repaint();
           st=conn.prepareStatement(y);
              r = st.executeQuery();
            tb4.setModel(DbUtils.resultSetToTableModel(r));
            
             }
             else if(y.contains("desc ")){
        
             kk.removeAll();
            kk.revalidate();
            kk.repaint();
            kk.add(kk8);
            kk.revalidate();
            kk.repaint();
           st=conn.prepareStatement(y);
              r = st.executeQuery();
            tb4.setModel(DbUtils.resultSetToTableModel(r));
            
             }
             else{conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+tb.getValueAt(i,0).toString()+"", "root", "");
            String query=y;
            st=conn.prepareStatement(query);
            st.execute();
            JOptionPane.showMessageDialog(null,"Excecuted");
             showdb();
            }
        } catch (SQLException ex) {
            Logger.getLogger(create_database.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null,ex);
            kk.removeAll();
            kk.revalidate();
            kk.repaint();
            kk.add(kk3);
            kk.revalidate();
            kk.repaint();
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
         try {
            int i=tb.getSelectedRow();
            String y=ta.getText().toLowerCase();
            
           
            if(y.contains("select")){
             kk.removeAll();
            kk.revalidate();
            kk.repaint();
            kk.add(kk8);
            kk.revalidate();
            kk.repaint();
           st=conn.prepareStatement(y);
              r = st.executeQuery();
            tb4.setModel(DbUtils.resultSetToTableModel(r));
            }
             else if(y.contains("show ")){
           
             kk.removeAll();
            kk.revalidate();
            kk.repaint();
            kk.add(kk8);
            kk.revalidate();
            kk.repaint();
           st=conn.prepareStatement(y);
              r = st.executeQuery();
            tb4.setModel(DbUtils.resultSetToTableModel(r));
            
             }
             else if(y.contains("desc ")){
        
             kk.removeAll();
            kk.revalidate();
            kk.repaint();
            kk.add(kk8);
            kk.revalidate();
            kk.repaint();
           st=conn.prepareStatement(y);
              r = st.executeQuery();
            tb4.setModel(DbUtils.resultSetToTableModel(r));
            
             }
            else{conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+tb.getValueAt(i,0).toString()+"", "root", "");
            String query=y;
            st=conn.prepareStatement(query);
            st.execute();
            JOptionPane.showMessageDialog(null,"excuted");
             showdb();
            }
        } catch (SQLException ex) {
            Logger.getLogger(create_database.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int i=tb.getSelectedRow();
        if(!tb.isColumnSelected(0)||!tb2.isColumnSelected(0)){
        JOptionPane.showMessageDialog(null,"Select database to delete");
        }
        if(tb.isColumnSelected(0)&&!tb2.isColumnSelected(0)){
            try {
                conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "");
                 String query="drop database "+tb.getValueAt(i, 0)+"";
                 st=conn.prepareStatement(query);
                 st.execute();
                 showdb();
               
            } catch (SQLException ex) {
                Logger.getLogger(create_database.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(tb.isColumnSelected(0)&&tb.isColumnSelected(0)){
         try {
                conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+tb.getValueAt(i, 0)+"", "root", "");
                 String query="drop table "+tb2.getValueAt(i, 0).toString()+"";
                 st=conn.prepareStatement(query);
                 st.execute();
                showtb();
                showtb2();
            } catch (SQLException ex) {
                Logger.getLogger(create_database.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed
  public void showtb(){
   int i=tb.getSelectedRow();
        try {
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+tb.getValueAt(i,0).toString()+"", "root", "");
            String query="show tables";
            st=conn.prepareStatement(query);
            rs=st.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(create_database.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(null,ex);
        }
         
         tb2.setModel(DbUtils.resultSetToTableModel(rs));
        tb3.setVisible(false);
        
          
         tbt.setText(tb2.getValueAt(0, 0).toString());
         kk.removeAll();
            kk.revalidate();
            kk.repaint();
            kk.add(kk7);
            kk.revalidate();
            kk.repaint();
  }
  public void showtb2(){
   tb3.setVisible(true);
         int i=tb.getSelectedRow();
          try {
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+tb.getValueAt(i,0).toString()+"", "root", "");
                          int v=tb2.getSelectedRow();

            String query="desc "+tb2.getValueAt(v, 0)+"";
            st=conn.prepareStatement(query);
            rs=st.executeQuery();
             String query1="select * from "+tb2.getValueAt(v, 0)+"";
            st=conn.prepareStatement(query1);
              r = st.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(create_database.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(null,ex);
        }
          kk.removeAll();
            kk.revalidate();
            kk.repaint();
            kk.add(kk8);
            kk.revalidate();
            kk.repaint();
           tb3.setModel(DbUtils.resultSetToTableModel(rs));
            tb4.setModel(DbUtils.resultSetToTableModel(r));
  }
  public void showtb3(){}
    public void showdb() {
        try {
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "");
            String query="show databases";
            st=conn.prepareStatement(query);
            rs=st.executeQuery();
            tb.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(create_database.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null,ex);
        }
  }     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create_database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create_database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create_database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create_database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new create_database().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(create_database.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> col;
    public static javax.swing.JTextField db;
    private javax.swing.JLabel he;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel kk;
    private javax.swing.JPanel kk2;
    private javax.swing.JPanel kk3;
    private javax.swing.JPanel kk4;
    private javax.swing.JPanel kk5;
    private javax.swing.JPanel kk6;
    private javax.swing.JPanel kk7;
    private javax.swing.JPanel kk8;
    private javax.swing.JScrollPane ll;
    public static javax.swing.JTextField rows;
    private javax.swing.JTextArea ta;
    public static javax.swing.JTextField table1;
    private javax.swing.JTextArea tak;
    private javax.swing.JTable tb;
    private javax.swing.JTable tb2;
    private javax.swing.JTable tb3;
    private javax.swing.JTable tb4;
    private javax.swing.JLabel tbt;
    private javax.swing.JTextArea tc;
    // End of variables declaration//GEN-END:variables
}
