/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database;

import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author 17g01acs028
 */
public class tables extends javax.swing.JFrame {

    /**
     * Creates new form tables
     */
    int x;
    int y;
    public tables() {
        
        initComponents();
       jj.removeAll();
       jj.revalidate();
       jj.repaint();
       scro.setVisible(false);
        
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        scro = new javax.swing.JScrollPane();
        jj = new javax.swing.JPanel();
        chack = new javax.swing.JPanel();
        j1d = new javax.swing.JComboBox<>();
        j1e = new javax.swing.JRadioButton();
        j1c = new javax.swing.JRadioButton();
        j1b = new javax.swing.JTextField();
        j1a = new javax.swing.JComboBox<>();
        j1 = new javax.swing.JTextField();
        chack1 = new javax.swing.JPanel();
        j2d = new javax.swing.JComboBox<>();
        j2e = new javax.swing.JRadioButton();
        j2c = new javax.swing.JRadioButton();
        j2b = new javax.swing.JTextField();
        j2a = new javax.swing.JComboBox<>();
        j2 = new javax.swing.JTextField();
        chack2 = new javax.swing.JPanel();
        j3d = new javax.swing.JComboBox<>();
        j3e = new javax.swing.JRadioButton();
        j3c = new javax.swing.JRadioButton();
        j3b = new javax.swing.JTextField();
        j3a = new javax.swing.JComboBox<>();
        j3 = new javax.swing.JTextField();
        chack3 = new javax.swing.JPanel();
        j4d = new javax.swing.JComboBox<>();
        j4e = new javax.swing.JRadioButton();
        j4c = new javax.swing.JRadioButton();
        j4b = new javax.swing.JTextField();
        j4a = new javax.swing.JComboBox<>();
        j4 = new javax.swing.JTextField();
        chack4 = new javax.swing.JPanel();
        j5d = new javax.swing.JComboBox<>();
        j5e = new javax.swing.JRadioButton();
        j5c = new javax.swing.JRadioButton();
        j5b = new javax.swing.JTextField();
        j5a = new javax.swing.JComboBox<>();
        j5 = new javax.swing.JTextField();
        chack5 = new javax.swing.JPanel();
        j6d = new javax.swing.JComboBox<>();
        j6e = new javax.swing.JRadioButton();
        j6c = new javax.swing.JRadioButton();
        j6b = new javax.swing.JTextField();
        j6a = new javax.swing.JComboBox<>();
        j6 = new javax.swing.JTextField();
        chack9 = new javax.swing.JPanel();
        j7d = new javax.swing.JComboBox<>();
        j7e = new javax.swing.JRadioButton();
        j7c = new javax.swing.JRadioButton();
        j7b = new javax.swing.JTextField();
        j7a = new javax.swing.JComboBox<>();
        j7 = new javax.swing.JTextField();
        chack8 = new javax.swing.JPanel();
        j8d = new javax.swing.JComboBox<>();
        j8e = new javax.swing.JRadioButton();
        j8c = new javax.swing.JRadioButton();
        j8b = new javax.swing.JTextField();
        j8a = new javax.swing.JComboBox<>();
        j8 = new javax.swing.JTextField();
        chack7 = new javax.swing.JPanel();
        j9d = new javax.swing.JComboBox<>();
        j9e = new javax.swing.JRadioButton();
        j9c = new javax.swing.JRadioButton();
        j9b = new javax.swing.JTextField();
        j9a = new javax.swing.JComboBox<>();
        j9 = new javax.swing.JTextField();
        chack6 = new javax.swing.JPanel();
        j10d = new javax.swing.JComboBox<>();
        j10e = new javax.swing.JRadioButton();
        j10c = new javax.swing.JRadioButton();
        j10b = new javax.swing.JTextField();
        j10a = new javax.swing.JComboBox<>();
        j10 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        g = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel5.setText("A.I");

        jLabel2.setText("Index");

        jLabel3.setText("Null");

        jLabel4.setText("type");

        jLabel1.setText("Name");

        jLabel6.setText("lenght/values");

        jj.setBackground(new java.awt.Color(0, 255, 255));

        j1d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRIMARY", "UNIQUE", "FULLTEXT", "INDEX", "SPATIAL" }));

        j1a.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INT", "VARCHAR", "STRING", "BIGINT", "DATE", "DOUBLE", "FLOAT", "TEXT", "CHAR" }));

        javax.swing.GroupLayout chackLayout = new javax.swing.GroupLayout(chack);
        chack.setLayout(chackLayout);
        chackLayout.setHorizontalGroup(
            chackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chackLayout.createSequentialGroup()
                .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(j1a, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(j1b, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(j1c)
                .addGap(107, 107, 107)
                .addComponent(j1d, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(j1e)
                .addGap(37, 37, 37))
        );
        chackLayout.setVerticalGroup(
            chackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(j1b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(j1e)
                .addComponent(j1d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j1c))
        );

        j2d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRIMARY", "UNIQUE", "FULLTEXT", "INDEX", "SPATIAL" }));

        j2a.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INT", "VARCHAR", "STRING", "BIGINT", "DATE", "DOUBLE", "FLOAT", "TEXT", "CHAR" }));

        javax.swing.GroupLayout chack1Layout = new javax.swing.GroupLayout(chack1);
        chack1.setLayout(chack1Layout);
        chack1Layout.setHorizontalGroup(
            chack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack1Layout.createSequentialGroup()
                .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(j2a, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(j2b, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(j2c)
                .addGap(107, 107, 107)
                .addComponent(j2d, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(j2e)
                .addGap(37, 37, 37))
        );
        chack1Layout.setVerticalGroup(
            chack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(j2b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j2a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(j2e)
                .addComponent(j2d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j2c))
        );

        j3d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRIMARY", "UNIQUE", "FULLTEXT", "INDEX", "SPATIAL" }));

        j3a.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INT", "VARCHAR", "STRING", "BIGINT", "DATE", "DOUBLE", "FLOAT", "TEXT", "CHAR" }));

        javax.swing.GroupLayout chack2Layout = new javax.swing.GroupLayout(chack2);
        chack2.setLayout(chack2Layout);
        chack2Layout.setHorizontalGroup(
            chack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack2Layout.createSequentialGroup()
                .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(j3a, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(j3b, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(j3c)
                .addGap(107, 107, 107)
                .addComponent(j3d, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(j3e)
                .addGap(37, 37, 37))
        );
        chack2Layout.setVerticalGroup(
            chack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(j3b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j3a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(j3e)
                .addComponent(j3d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j3c))
        );

        j4d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRIMARY", "UNIQUE", "FULLTEXT", "INDEX", "SPATIAL" }));

        j4a.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INT", "VARCHAR", "STRING", "BIGINT", "DATE", "DOUBLE", "FLOAT", "TEXT", "CHAR" }));

        javax.swing.GroupLayout chack3Layout = new javax.swing.GroupLayout(chack3);
        chack3.setLayout(chack3Layout);
        chack3Layout.setHorizontalGroup(
            chack3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack3Layout.createSequentialGroup()
                .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(j4a, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(j4b, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(j4c)
                .addGap(107, 107, 107)
                .addComponent(j4d, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(j4e)
                .addGap(37, 37, 37))
        );
        chack3Layout.setVerticalGroup(
            chack3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(j4b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j4a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(j4e)
                .addComponent(j4d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j4c))
        );

        j5d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRIMARY", "UNIQUE", "FULLTEXT", "INDEX", "SPATIAL" }));

        j5a.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INT", "VARCHAR", "STRING", "BIGINT", "DATE", "DOUBLE", "FLOAT", "TEXT", "CHAR" }));

        javax.swing.GroupLayout chack4Layout = new javax.swing.GroupLayout(chack4);
        chack4.setLayout(chack4Layout);
        chack4Layout.setHorizontalGroup(
            chack4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack4Layout.createSequentialGroup()
                .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(j5a, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(j5b, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(j5c)
                .addGap(107, 107, 107)
                .addComponent(j5d, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(j5e)
                .addGap(37, 37, 37))
        );
        chack4Layout.setVerticalGroup(
            chack4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(j5b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j5a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(j5e)
                .addComponent(j5d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j5c))
        );

        j6d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRIMARY", "UNIQUE", "FULLTEXT", "INDEX", "SPATIAL" }));

        j6a.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INT", "VARCHAR", "STRING", "BIGINT", "DATE", "DOUBLE", "FLOAT", "TEXT", "CHAR" }));

        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chack5Layout = new javax.swing.GroupLayout(chack5);
        chack5.setLayout(chack5Layout);
        chack5Layout.setHorizontalGroup(
            chack5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack5Layout.createSequentialGroup()
                .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(j6a, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(j6b, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(j6c)
                .addGap(107, 107, 107)
                .addComponent(j6d, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(j6e)
                .addGap(37, 37, 37))
        );
        chack5Layout.setVerticalGroup(
            chack5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(j6b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j6a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(j6e)
                .addComponent(j6d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j6c))
        );

        j7d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRIMARY", "UNIQUE", "FULLTEXT", "INDEX", "SPATIAL" }));

        j7a.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INT", "VARCHAR", "STRING", "BIGINT", "DATE", "DOUBLE", "FLOAT", "TEXT", "CHAR" }));

        javax.swing.GroupLayout chack9Layout = new javax.swing.GroupLayout(chack9);
        chack9.setLayout(chack9Layout);
        chack9Layout.setHorizontalGroup(
            chack9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack9Layout.createSequentialGroup()
                .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(j7a, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(j7b, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(j7c)
                .addGap(107, 107, 107)
                .addComponent(j7d, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(j7e)
                .addGap(37, 37, 37))
        );
        chack9Layout.setVerticalGroup(
            chack9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(j7b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j7a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(j7e)
                .addComponent(j7d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j7c))
        );

        j8d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRIMARY", "UNIQUE", "FULLTEXT", "INDEX", "SPATIAL" }));

        j8a.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INT", "VARCHAR", "STRING", "BIGINT", "DATE", "DOUBLE", "FLOAT", "TEXT", "CHAR" }));

        javax.swing.GroupLayout chack8Layout = new javax.swing.GroupLayout(chack8);
        chack8.setLayout(chack8Layout);
        chack8Layout.setHorizontalGroup(
            chack8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack8Layout.createSequentialGroup()
                .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(j8a, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(j8b, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(j8c)
                .addGap(107, 107, 107)
                .addComponent(j8d, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(j8e)
                .addGap(37, 37, 37))
        );
        chack8Layout.setVerticalGroup(
            chack8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(j8b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j8a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(j8e)
                .addComponent(j8d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j8c))
        );

        j9d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRIMARY", "UNIQUE", "FULLTEXT", "INDEX", "SPATIAL" }));

        j9a.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INT", "VARCHAR", "STRING", "BIGINT", "DATE", "DOUBLE", "FLOAT", "TEXT", "CHAR" }));

        javax.swing.GroupLayout chack7Layout = new javax.swing.GroupLayout(chack7);
        chack7.setLayout(chack7Layout);
        chack7Layout.setHorizontalGroup(
            chack7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack7Layout.createSequentialGroup()
                .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(j9a, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(j9b, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(j9c)
                .addGap(107, 107, 107)
                .addComponent(j9d, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(j9e)
                .addGap(37, 37, 37))
        );
        chack7Layout.setVerticalGroup(
            chack7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(j9b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j9a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(j9e)
                .addComponent(j9d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j9c))
        );

        j10d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRIMARY", "UNIQUE", "FULLTEXT", "INDEX", "SPATIAL" }));

        j10a.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INT", "VARCHAR", "STRING", "BIGINT", "DATE", "DOUBLE", "FLOAT", "TEXT", "CHAR" }));

        javax.swing.GroupLayout chack6Layout = new javax.swing.GroupLayout(chack6);
        chack6.setLayout(chack6Layout);
        chack6Layout.setHorizontalGroup(
            chack6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack6Layout.createSequentialGroup()
                .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(j10a, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(j10b, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(j10c)
                .addGap(107, 107, 107)
                .addComponent(j10d, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(j10e)
                .addGap(37, 37, 37))
        );
        chack6Layout.setVerticalGroup(
            chack6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(j10b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j10a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chack6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(j10e)
                .addComponent(j10d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(j10c))
        );

        javax.swing.GroupLayout jjLayout = new javax.swing.GroupLayout(jj);
        jj.setLayout(jjLayout);
        jjLayout.setHorizontalGroup(
            jjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jjLayout.createSequentialGroup()
                .addGroup(jjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chack1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chack3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chack2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chack4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chack5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chack9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chack8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chack7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chack6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99))
        );
        jjLayout.setVerticalGroup(
            jjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jjLayout.createSequentialGroup()
                .addComponent(chack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chack1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(chack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chack3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chack4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chack5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chack6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chack7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chack8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chack9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 386, Short.MAX_VALUE))
        );

        scro.setViewportView(jj);

        jButton1.setText("create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Insert");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("generate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(46, 46, 46)
                .addComponent(jButton4)
                .addGap(270, 270, 270)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(g, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scro, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(904, 412));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

   
        Connection conn;
   
       try {
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+create_database.db.getText()+"", "root", "");
            PreparedStatement st;
            String name1 = null,name2 = null,name3 = null,name4 = null,name5 = null,name6 = null,name7 = null,name8 = null,name9 = null,name10 = null;
            String type1= null,type2= null,type3= null,type4= null,type5= null,type6= null,type7= null,type8= null,type9= null,type10= null;
            String num1= null,num2= null,num3= null,num4= null,num5= null,num6= null,num7= null,num8= null,num9= null,num10= null;
            if(j1.getText().isEmpty()){
            name1="";type1="";num1="";
            }else{
            name1=j1.getText();type1=j1a.getSelectedItem().toString().toLowerCase(Locale.ITALY);num1="("+j1b.getText()+")";
            }
            if(j1.getText().isEmpty()){
             name2="";type2="";num2="";
            }else{
              name2=","+j2.getText();type2=j2a.getSelectedItem().toString().toLowerCase(Locale.ITALY);num2="("+j2b.getText()+")";
            }
            if(j3.getText().isEmpty()){
             name3="";type3="";num3="";
            }else{
              name3=","+j3.getText();type3=j3a.getSelectedItem().toString().toLowerCase(Locale.ITALY);num3="("+j3b.getText()+")";
            }
            if(j4.getText().isEmpty()){
             name4="";type4="";num4="";
            }else{
              name4=","+j4.getText();type4=j4a.getSelectedItem().toString().toLowerCase(Locale.ITALY);num4="("+j4b.getText()+")";
            }
            if(j5.getText().isEmpty()){
             name5="";type5="";num5="";
            }else{
              name5=","+j5.getText();type5=j5a.getSelectedItem().toString().toLowerCase(Locale.ITALY);num5="("+j5b.getText()+")";
            }
            if(j10.getText().isEmpty()){
             name6="";type6="";num6="";
            }else{
              name6=","+j10.getText();type6=j10a.getSelectedItem().toString().toLowerCase(Locale.ITALY);num6="("+j10b.getText()+")";
            }
            if(j9.getText().isEmpty()){
             name7="";type7="";num7="";
            }else{
              name7=","+j9.getText();type7=j9a.getSelectedItem().toString().toLowerCase(Locale.ITALY);num7="("+j9b.getText()+")";
            }
            if(j8.getText().isEmpty()){
             name8="";type8="";num8="";
            }else{
              name8=","+j8.getText();type8=j8a.getSelectedItem().toString().toLowerCase(Locale.ITALY);num8="("+j8b.getText()+")";
            }
            if(j7.getText().isEmpty()){
             name9="";type9="";num9="";
            }else{
              name9=","+j7.getText();type9=j7a.getSelectedItem().toString().toLowerCase(Locale.ITALY);num9="("+j7b.getText()+")";
            }
            if(j6.getText().isEmpty()){
             name10="";type10="";num10="";
            }else{
              name10=","+j6.getText();type10=j6a.getSelectedItem().toString().toLowerCase(Locale.ITALY);num10="("+j6b.getText()+")";
            }
            String query="create table "+create_database.table1.getText()+"("+name1+" "+type1+""+num1+""+name2+" "+type2+""+num2+""+name3+" "+type3+""+num3+""+name4+" "+type4+""+num4+""+name5+" "+type5+""+num5+""+name6+" "+type6+""+num6+""+name7+" "+type7+""+num7+""+name8+" "+type8+""+num8+""+name9+" "+type9+""+num9+""+name10+" "+type10+""+num10+")";
                 System.out.println(query);
        st=conn.prepareStatement(query);
        st.execute();
            System.out.println(query);
            create_database b=new create_database();
            b.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
           Logger.getLogger(tables.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex);
       }
        
        
          
       
    }//GEN-LAST:event_jButton1ActionPerformed
                            

 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   if(JOptionPane.showConfirmDialog(null, "Do you want to close without saving ", "MESSAGE",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){     try {
            this.setVisible(false);
            // TODO add your handling code here:
            create_database d=new create_database();
            d.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(tables.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null,ex);
        }}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         scro.setVisible(true);
       String y= create_database.rows.getText();
         x=Integer.parseInt(y);
 jj.removeAll();
 jj.repaint();
 jj.revalidate(); 
if(x==1){
 
jj.add(chack);
}
if(x==2){
jj.add(chack);jj.add(chack1);
}
if(x==3){
jj.add(chack);jj.add(chack1);jj.add(chack2);
}
if(x==4){
jj.add(chack);jj.add(chack1);jj.add(chack2);jj.add(chack3);
}
if(x==5){
jj.add(chack);jj.add(chack1);jj.add(chack2);jj.add(chack3);jj.add(chack4);
}
if(x==6){
jj.add(chack);jj.add(chack1);jj.add(chack2);jj.add(chack3);jj.add(chack4);jj.add(chack5);
}
if(x==7){
jj.add(chack);jj.add(chack1);jj.add(chack2);jj.add(chack3);jj.add(chack4);jj.add(chack5);jj.add(chack6);
}
if(x==8){
jj.add(chack);jj.add(chack1);jj.add(chack2);jj.add(chack3);jj.add(chack4);jj.add(chack5);jj.add(chack6);jj.add(chack7);
}
if(x==9){
jj.add(chack);jj.add(chack1);jj.add(chack2);jj.add(chack3);jj.add(chack4);jj.add(chack5);jj.add(chack6);jj.add(chack7);jj.add(chack8);
}
if(x==9){
jj.add(chack);jj.add(chack1);jj.add(chack2);jj.add(chack3);jj.add(chack4);jj.add(chack5);jj.add(chack6);jj.add(chack7);jj.add(chack8);
}
if(x==10){
jj.add(chack);jj.add(chack1);jj.add(chack2);jj.add(chack3);jj.add(chack4);jj.add(chack5);jj.add(chack6);jj.add(chack7);jj.add(chack8);jj.add(chack9);
}
 g.setText(Integer.toString(x)+ "rows");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        int y=x+1;
        jj.repaint();
 jj.revalidate(); 
        if(y==1){
 
jj.add(chack);
}
if(y==2){
jj.add(chack1);
y=y+1;

}
if(y==3){
jj.add(chack2);
}
if(y==4){
jj.add(chack3);
}
if(y==5){
jj.add(chack4);
}
if(y==6){
jj.add(chack5);
}
if(y==7){
jj.add(chack6);
}
if(y==8){
jj.add(chack7);
}
if(y==9){
jj.add(chack8);
}
if(y==9){
jj.add(chack8);
}
if(y==10){
jj.add(chack9);
}x=y;
g.setText(y+ "rows");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void j6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tables().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chack;
    private javax.swing.JPanel chack1;
    private javax.swing.JPanel chack2;
    private javax.swing.JPanel chack3;
    private javax.swing.JPanel chack4;
    private javax.swing.JPanel chack5;
    private javax.swing.JPanel chack6;
    private javax.swing.JPanel chack7;
    private javax.swing.JPanel chack8;
    private javax.swing.JPanel chack9;
    private javax.swing.JLabel g;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j10;
    private javax.swing.JComboBox<String> j10a;
    private javax.swing.JTextField j10b;
    private javax.swing.JRadioButton j10c;
    private javax.swing.JComboBox<String> j10d;
    private javax.swing.JRadioButton j10e;
    private javax.swing.JComboBox<String> j1a;
    private javax.swing.JTextField j1b;
    private javax.swing.JRadioButton j1c;
    private javax.swing.JComboBox<String> j1d;
    private javax.swing.JRadioButton j1e;
    private javax.swing.JTextField j2;
    private javax.swing.JComboBox<String> j2a;
    private javax.swing.JTextField j2b;
    private javax.swing.JRadioButton j2c;
    private javax.swing.JComboBox<String> j2d;
    private javax.swing.JRadioButton j2e;
    private javax.swing.JTextField j3;
    private javax.swing.JComboBox<String> j3a;
    private javax.swing.JTextField j3b;
    private javax.swing.JRadioButton j3c;
    private javax.swing.JComboBox<String> j3d;
    private javax.swing.JRadioButton j3e;
    private javax.swing.JTextField j4;
    private javax.swing.JComboBox<String> j4a;
    private javax.swing.JTextField j4b;
    private javax.swing.JRadioButton j4c;
    private javax.swing.JComboBox<String> j4d;
    private javax.swing.JRadioButton j4e;
    private javax.swing.JTextField j5;
    private javax.swing.JComboBox<String> j5a;
    private javax.swing.JTextField j5b;
    private javax.swing.JRadioButton j5c;
    private javax.swing.JComboBox<String> j5d;
    private javax.swing.JRadioButton j5e;
    private javax.swing.JTextField j6;
    private javax.swing.JComboBox<String> j6a;
    private javax.swing.JTextField j6b;
    private javax.swing.JRadioButton j6c;
    private javax.swing.JComboBox<String> j6d;
    private javax.swing.JRadioButton j6e;
    private javax.swing.JTextField j7;
    private javax.swing.JComboBox<String> j7a;
    private javax.swing.JTextField j7b;
    private javax.swing.JRadioButton j7c;
    private javax.swing.JComboBox<String> j7d;
    private javax.swing.JRadioButton j7e;
    private javax.swing.JTextField j8;
    private javax.swing.JComboBox<String> j8a;
    private javax.swing.JTextField j8b;
    private javax.swing.JRadioButton j8c;
    private javax.swing.JComboBox<String> j8d;
    private javax.swing.JRadioButton j8e;
    private javax.swing.JTextField j9;
    private javax.swing.JComboBox<String> j9a;
    private javax.swing.JTextField j9b;
    private javax.swing.JRadioButton j9c;
    private javax.swing.JComboBox<String> j9d;
    private javax.swing.JRadioButton j9e;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jj;
    private javax.swing.JScrollPane scro;
    // End of variables declaration//GEN-END:variables
}
